OpenAuth.WebApi/Areas/SSO/Controllers/LoginController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using OpenAuth.App.SSO;

namespace OpenAuth.WebApi.Areas.SSO.Controllers
{

    /// <summary>
    ///  SSO自带的登录处理
    /// <para>第三方网站如果自己不开发登录界面，可直接跳转到本界面进行登录</para>
    /// </summary>
    public class LoginController : Controller
    {
        private AppInfoService _appInfoService;

        private LoginParse _loginParse;

        private const string AppInfo = "AppInfo";

        //加载登录界面
        public ActionResult Index(string appKey = "", string username = "")
        {
            TempData[AppInfo] = _appInfoService.Get(appKey);

            var viewModel = new PassportLoginRequest
            {
                AppKey = appKey,
                Account = username,
            };

            return View(viewModel);
        }

        //授权登录
        [HttpPost]
        public ActionResult Index(PassportLoginRequest model)
        {
            var result = _loginParse.Do(model);

            if (result.Code ==200)
            {
                var redirectUrl = string.Format("{0}?token={1}&sessionusername={2}", result.ReturnUrl, result.Token, model.Account);

                //跳转默认回调页面
                return Redirect(redirectUrl);
            }

            TempData[AppInfo] = _appInfoService.Get(model.AppKey);
            return View(model);
        }
    }
}

OpenAuth.WebApi/Areas/SSO/Views/Login/Index.cshtml
@using OpenAuth.App.SSO
@model  PassportLoginRequest
@{
    var appinfo = TempData["AppInfo"] as AppInfo;
}

<head>
    <link href="/Areas/SSO/Content/bootstrap.min.css" rel="stylesheet">
    <link href="/Areas/SSO/Content/Site.css" rel="stylesheet">
    <style id="igtranslator-color" type="text/css"></style>
    <title>OpenAuth.net统一登录授权中心</title>
</head>
<html>
<body>
    <div class="row">

        @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "form-horizontal", style = "max-width: 390px; padding-top:50px;  margin: 0 auto;" }))
        {
            if (appinfo != null)
            {
                <div class="form-group">
                    <div class="col-md-11 col-md-offset-1">
                        <div style="text-align: center;">
                            <img src="@appinfo.Icon" style="width: 128px; height: 128px;" title="@appinfo.Title">
                            <div class="caption">
                                <h3>@appinfo.Title</h3>
                                <p style="text-align: left;">
                                    <small>@appinfo.Remark</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            }

            <div class="form-group">
                <label class="col-md-3 control-label" for="UserName">用户名</label>
                <div class="col-md-9">
                    @Html.TextBoxFor(model => model.Account, new { @class = "form-control input-lg", style = "width: 280px" })
                    @Html.HiddenFor(model => model.AppKey)
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-3 control-label" for="Password">密码</label>
                <div class="col-md-9">
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control input-lg", style = "width: 280px" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-9 col-md-offset-3">
                    @Html.ValidationSummary(false)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-9 col-md-offset-3 ">
                    <button type="submit" class="btn btn-primary">登录</button>
                </div>
            </div>
        }

    </div>
</body>
</html>